name: Greeting from Chan Tsun Hin
on: push
jobs:
my-job:
name: My Job
runs-on: ubuntu-latest
steps:
- name: Print a greeting
env:
MY_VAR: Hi there! My name is
FIRST_NAME: Chan
MIDDLE_NAME: Tsun
LAST_NAME: Hin
run: |
echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
